phase-4-rails/wk1/01-intro/intro_to_rails/config/routes.rb
Rails.application.routes.draw do
  resources :songs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

phase-4-rails/wk1/01-intro/intro_to_rails/app/models/artist.rb
class Artist < ApplicationRecord
end

phase-4-rails/wk1/01-intro/intro_to_rails/app/models/song.rb
class Song < ApplicationRecord
end

phase-4-rails/wk1/01-intro/intro_to_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

phase-4-rails/wk1/01-intro/intro_to_rails/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
end

phase-4-rails/wk1/01-intro/intro_to_rails/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title)
    end
end

phase-4-rails/wk1/01-intro/intro_to_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

phase-4-rails/wk1/01-intro/intro_to_rails/app/helpers/artists_helper.rb
module ArtistsHelper
end

phase-4-rails/wk1/01-intro/intro_to_rails/app/helpers/songs_helper.rb
module SongsHelper
end

phase-4-rails/wk1/01-intro/intro_to_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroToRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

phase-4-rails/wk1/01-intro/intro_to_rails/app/views/songs/_form.html.erb
<%= form_with(model: song) do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

phase-4-rails/wk1/01-intro/intro_to_rails/app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

phase-4-rails/wk1/01-intro/intro_to_rails/app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

phase-4-rails/wk1/01-intro/intro_to_rails/app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

phase-4-rails/wk1/01-intro/intro_to_rails/app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>